name: bulk_delete
description: A command-line app to delete files and folders based on regex patterns
version: 0.1.0
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  args: ^2.3.0
  glob: ^2.1.0
  path: ^1.8.0